"""Initial migration

Revision ID: 05fd5c632951
Revises: 1a1a6a94c8d6
Create Date: 2025-12-15 17:20:50.598477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05fd5c632951'
down_revision = '1a1a6a94c8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
