"""Add Receptionist model

Revision ID: 06741d432e59
Revises: 05fd5c632951
Create Date: 2026-03-31 11:36:28.725500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '06741d432e59'
down_revision = '05fd5c632951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_hash', sa.String(length=100), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('action_timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('ai_service', sa.String(length=50), nullable=True),
    sa.Column('ai_model_version', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('error_details', sa.String(length=500), nullable=True),
    sa.Column('context', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_audit_logs_action_timestamp'), ['action_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_audit_logs_user_id_hash'), ['user_id_hash'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('intent_categories', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_conversation_id'), ['conversation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_chat_sessions_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('receptionists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('message_number', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('intent_category', sa.String(length=100), nullable=True),
    sa.Column('interaction_summary', sa.String(length=500), nullable=True),
    sa.Column('action_triggered', sa.String(length=100), nullable=True),
    sa.Column('action_successful', sa.Boolean(), nullable=True),
    sa.Column('was_escalated', sa.Boolean(), nullable=True),
    sa.Column('resolution_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_sessions.conversation_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)

    op.create_table('note_interpretations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.String(length=50), nullable=False),
    sa.Column('original_note_text', sa.Text(), nullable=False),
    sa.Column('formatted_note', sa.Text(), nullable=True),
    sa.Column('clinical_summary', sa.Text(), nullable=True),
    sa.Column('patient_friendly_summary', sa.Text(), nullable=True),
    sa.Column('extracted_symptoms', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('extracted_diagnoses', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('extracted_medications', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('extracted_vitals', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('ai_model_version', sa.String(length=100), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_processing_timestamp', sa.DateTime(), nullable=True),
    sa.Column('ai_processing_latency_ms', sa.Integer(), nullable=True),
    sa.Column('clinician_approved', sa.Boolean(), nullable=True),
    sa.Column('clinician_approved_by', sa.String(length=50), nullable=True),
    sa.Column('clinician_approved_at', sa.DateTime(), nullable=True),
    sa.Column('clinician_edited', sa.Boolean(), nullable=True),
    sa.Column('clinician_edits_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note_interpretations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_interpretations_clinician_approved'), ['clinician_approved'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_interpretations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_interpretations_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_interpretations_note_id'), ['note_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_note_interpretations_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_interpretations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_interpretations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_note_interpretations_note_id'))
        batch_op.drop_index(batch_op.f('ix_note_interpretations_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_note_interpretations_created_at'))
        batch_op.drop_index(batch_op.f('ix_note_interpretations_clinician_approved'))

    op.drop_table('note_interpretations')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_conversation_id'))

    op.drop_table('chat_messages')
    op.drop_table('receptionists')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_started_at'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_conversation_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('ai_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_audit_logs_user_id_hash'))
        batch_op.drop_index(batch_op.f('ix_ai_audit_logs_action_timestamp'))
        batch_op.drop_index(batch_op.f('ix_ai_audit_logs_action'))

    op.drop_table('ai_audit_logs')
    # ### end Alembic commands ###
